name: Nightly

# run the vanilla build pipeline every night on the master branch

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable_build.yml
    with:
      ref: ${{ 'master' }}
    secrets: inherit
