name: Release

# run the Release pipeline when a release is created, and attach artifacts

on:
  release:
    types: [published]  # Triggers when a release is published
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  build_release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/milsanore/tradercppbuild:v1.8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Conan cache
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.*') }}-Release

      - name: Install conan dependencies
        run: |
          set -e
          rm -rf build
          conan profile detect --force
          conan install . --lockfile=conan.lock --build=missing -s build_type=Release

      - name: Build
        run: |
          set -e
          cmake --preset=release
          cmake --build --preset=release
          chmod +x build/Release/tradercpp

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/tradercpp
          token: ${{ secrets.PAT_RELEASE_20261020 }}

      - name: Prune Conan cache
        run: |
          conan cache clean --build
